# Kitty — config personal
# Fuente: Nerd Font para íconos (LazyVim, p10k, yazi, eza)
font_family MesloLGS Nerd Font Mono
font_size 11.0

# Black Metal theme — Gorgoroth
include black-metal-gorgoroth.conf

# ── Comodidad ──
scrollback_lines 10000
copy_on_select yes
cursor_shape beam
cursor_blink_interval 0
cursor_trail 3
window_padding_width 0

# ── Tabs y ventana ──
tab_bar_style powerline
hide_window_decorations titlebar-only